version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-local
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '1234'
      # TZ: "Asia/Seoul"
    volumes:
      - "./mysql.conf:/etc/mysql/conf.d/z_my.cnf"
      - "./db_data:/var/lib/mysql"
      - "./log:/var/log/mysql"
      # - "./backup.sql:/docker-entrypoint-initdb.d/dump.sql"